#!/bin/bash

if [ $# != 1 ]; then
    echo "Pass in keyvault to execute"
    exit 1
fi

read -p "What query world would you like to use to delete secrets in $1? "
if [[ "$REPLY" = "" ]]; then
    exit 1
fi

SECRETS=$(az keyvault secret list --vault-name $1 -o json | jq .[] | jq "select((.name) and (.name | contains(\"$REPLY\")))" | jq -r .name)

if [ -z "$SECRETS" ]; then
    echo "There was no secrets found that have '$REPLY' in them"
    exit 0
fi

echo "The following secrets will be deleted:"
for SECRET in $SECRETS; do
    echo $SECRET
done

read -p "Are you sure you want to delete these secrets [y/N]?"
if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
    exit 1
fi

read -p "Are you REALLY sure.  There is no coming back [y/N]?"
if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
    exit 1
fi

for SECRET in $SECRETS; do
    echo "Deleting $SECRET"
    az keyvault secret delete --vault-name $1 --name $SECRET
done

