---
kind: Namespace
apiVersion: v1
metadata:
  name: hello-world
  labels:
    name: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: hello-world
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 5
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: "gcr.io/google-samples/hello-app:2.0"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello-world
  labels:
    app: hello
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: hello-world
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - ${K8S_FQDN}
    secretName: tls-secret
  rules:
  - host: ${K8S_FQDN}
    http:
      paths:
      - backend:
          serviceName: hello-service
          servicePort: 80
        path: /(.*)
